// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="conv2d,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=39661,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=216,HLS_SYN_LUT=331,HLS_VERSION=2018_2}" *)

module conv2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        kernel_address0,
        kernel_ce0,
        kernel_q0,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] in_r_address0;
output   in_r_ce0;
input  [31:0] in_r_q0;
output  [3:0] kernel_address0;
output   kernel_ce0;
input  [31:0] kernel_q0;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_r_ce0;
reg kernel_ce0;
reg out_r_ce0;
reg out_r_we0;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] i_1_fu_158_p2;
reg   [4:0] i_1_reg_316;
wire    ap_CS_fsm_state2;
wire   [10:0] tmp_5_fu_188_p2;
reg   [10:0] tmp_5_reg_321;
wire   [0:0] exitcond3_fu_152_p2;
wire   [4:0] j_1_fu_200_p2;
reg   [4:0] j_1_reg_329;
wire    ap_CS_fsm_state3;
wire   [1:0] ki_1_fu_216_p2;
reg   [1:0] ki_1_reg_337;
wire    ap_CS_fsm_state4;
wire   [4:0] tmp_4_fu_222_p2;
reg   [4:0] tmp_4_reg_342;
wire   [0:0] exitcond1_fu_210_p2;
wire   [4:0] tmp_s_fu_240_p2;
reg   [4:0] tmp_s_reg_347;
wire   [1:0] kj_1_fu_270_p2;
reg   [1:0] kj_1_reg_355;
wire    ap_CS_fsm_state5;
wire   [0:0] exitcond_fu_264_p2;
reg  signed [31:0] in_load_reg_370;
wire    ap_CS_fsm_state6;
reg  signed [31:0] kernel_load_reg_375;
wire   [31:0] tmp_1_fu_304_p2;
reg   [31:0] tmp_1_reg_380;
wire    ap_CS_fsm_state7;
wire   [31:0] sum_2_fu_308_p2;
wire    ap_CS_fsm_state8;
reg   [4:0] i_reg_81;
wire   [0:0] exitcond2_fu_194_p2;
reg   [4:0] j_reg_93;
reg   [31:0] sum_reg_105;
reg   [1:0] ki_reg_118;
reg   [31:0] sum_1_reg_129;
reg   [1:0] kj_reg_141;
wire  signed [63:0] tmp_7_cast_fu_255_p1;
wire   [63:0] tmp_6_fu_289_p1;
wire  signed [63:0] tmp_13_cast_fu_299_p1;
wire   [9:0] tmp_fu_164_p3;
wire   [5:0] tmp_3_fu_176_p3;
wire   [10:0] p_shl_cast_fu_172_p1;
wire   [10:0] p_shl1_cast_fu_184_p1;
wire   [4:0] ki_cast4_fu_206_p1;
wire   [3:0] tmp_9_fu_228_p3;
wire   [4:0] p_shl2_cast_fu_236_p1;
wire   [10:0] tmp_2_cast_fu_246_p1;
wire   [10:0] tmp_7_fu_250_p2;
wire   [4:0] kj_cast2_fu_260_p1;
wire   [4:0] tmp_8_fu_276_p2;
wire   [9:0] tmp_2_fu_282_p3;
wire   [4:0] tmp_10_fu_294_p2;
reg   [7:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_194_p2 == 1'd1))) begin
        i_reg_81 <= i_1_reg_316;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_81 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_reg_93 <= 5'd0;
    end else if (((exitcond1_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        j_reg_93 <= j_1_reg_329;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ki_reg_118 <= 2'd0;
    end else if (((exitcond_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ki_reg_118 <= ki_1_reg_337;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_210_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kj_reg_141 <= 2'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        kj_reg_141 <= kj_1_reg_355;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_210_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum_1_reg_129 <= sum_reg_105;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        sum_1_reg_129 <= sum_2_fu_308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        sum_reg_105 <= 32'd0;
    end else if (((exitcond_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_reg_105 <= sum_1_reg_129;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_316 <= i_1_fu_158_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_load_reg_370 <= in_r_q0;
        kernel_load_reg_375 <= kernel_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_1_reg_329 <= j_1_fu_200_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ki_1_reg_337 <= ki_1_fu_216_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kj_1_reg_355 <= kj_1_fu_270_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_1_reg_380 <= tmp_1_fu_304_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_210_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        tmp_4_reg_342 <= tmp_4_fu_222_p2;
        tmp_s_reg_347 <= tmp_s_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_152_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_321[10 : 1] <= tmp_5_fu_188_p2[10 : 1];
    end
end

always @ (*) begin
    if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_r_ce0 = 1'b1;
    end else begin
        in_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kernel_ce0 = 1'b1;
    end else begin
        kernel_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond3_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (exitcond2_fu_194_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_210_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign exitcond1_fu_210_p2 = ((ki_reg_118 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_194_p2 = ((j_reg_93 == 5'd30) ? 1'b1 : 1'b0);

assign exitcond3_fu_152_p2 = ((i_reg_81 == 5'd30) ? 1'b1 : 1'b0);

assign exitcond_fu_264_p2 = ((kj_reg_141 == 2'd3) ? 1'b1 : 1'b0);

assign i_1_fu_158_p2 = (i_reg_81 + 5'd1);

assign in_r_address0 = tmp_6_fu_289_p1;

assign j_1_fu_200_p2 = (j_reg_93 + 5'd1);

assign kernel_address0 = tmp_13_cast_fu_299_p1;

assign ki_1_fu_216_p2 = (ki_reg_118 + 2'd1);

assign ki_cast4_fu_206_p1 = ki_reg_118;

assign kj_1_fu_270_p2 = (kj_reg_141 + 2'd1);

assign kj_cast2_fu_260_p1 = kj_reg_141;

assign out_r_address0 = tmp_7_cast_fu_255_p1;

assign out_r_d0 = sum_reg_105;

assign p_shl1_cast_fu_184_p1 = tmp_3_fu_176_p3;

assign p_shl2_cast_fu_236_p1 = tmp_9_fu_228_p3;

assign p_shl_cast_fu_172_p1 = tmp_fu_164_p3;

assign sum_2_fu_308_p2 = (sum_1_reg_129 + tmp_1_reg_380);

assign tmp_10_fu_294_p2 = (tmp_s_reg_347 + kj_cast2_fu_260_p1);

assign tmp_13_cast_fu_299_p1 = $signed(tmp_10_fu_294_p2);

assign tmp_1_fu_304_p2 = ($signed(kernel_load_reg_375) * $signed(in_load_reg_370));

assign tmp_2_cast_fu_246_p1 = j_reg_93;

assign tmp_2_fu_282_p3 = {{tmp_4_reg_342}, {tmp_8_fu_276_p2}};

assign tmp_3_fu_176_p3 = {{i_reg_81}, {1'd0}};

assign tmp_4_fu_222_p2 = (ki_cast4_fu_206_p1 + i_reg_81);

assign tmp_5_fu_188_p2 = (p_shl_cast_fu_172_p1 - p_shl1_cast_fu_184_p1);

assign tmp_6_fu_289_p1 = tmp_2_fu_282_p3;

assign tmp_7_cast_fu_255_p1 = $signed(tmp_7_fu_250_p2);

assign tmp_7_fu_250_p2 = (tmp_5_reg_321 + tmp_2_cast_fu_246_p1);

assign tmp_8_fu_276_p2 = (kj_cast2_fu_260_p1 + j_reg_93);

assign tmp_9_fu_228_p3 = {{ki_reg_118}, {2'd0}};

assign tmp_fu_164_p3 = {{i_reg_81}, {5'd0}};

assign tmp_s_fu_240_p2 = (p_shl2_cast_fu_236_p1 - ki_cast4_fu_206_p1);

always @ (posedge ap_clk) begin
    tmp_5_reg_321[0] <= 1'b0;
end

endmodule //conv2d
