// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> conv2d::ap_ST_fsm_state1 = "1";
const sc_lv<8> conv2d::ap_ST_fsm_state2 = "10";
const sc_lv<8> conv2d::ap_ST_fsm_state3 = "100";
const sc_lv<8> conv2d::ap_ST_fsm_state4 = "1000";
const sc_lv<8> conv2d::ap_ST_fsm_state5 = "10000";
const sc_lv<8> conv2d::ap_ST_fsm_state6 = "100000";
const sc_lv<8> conv2d::ap_ST_fsm_state7 = "1000000";
const sc_lv<8> conv2d::ap_ST_fsm_state8 = "10000000";
const sc_lv<32> conv2d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_1 = "1";
const sc_lv<1> conv2d::ap_const_lv1_0 = "0";
const sc_lv<32> conv2d::ap_const_lv32_2 = "10";
const sc_lv<32> conv2d::ap_const_lv32_3 = "11";
const sc_lv<32> conv2d::ap_const_lv32_4 = "100";
const sc_lv<32> conv2d::ap_const_lv32_5 = "101";
const sc_lv<32> conv2d::ap_const_lv32_6 = "110";
const sc_lv<32> conv2d::ap_const_lv32_7 = "111";
const sc_lv<5> conv2d::ap_const_lv5_0 = "00000";
const sc_lv<1> conv2d::ap_const_lv1_1 = "1";
const sc_lv<2> conv2d::ap_const_lv2_0 = "00";
const sc_lv<5> conv2d::ap_const_lv5_1E = "11110";
const sc_lv<5> conv2d::ap_const_lv5_1 = "1";
const sc_lv<2> conv2d::ap_const_lv2_3 = "11";
const sc_lv<2> conv2d::ap_const_lv2_1 = "1";
const bool conv2d::ap_const_boolean_1 = true;

conv2d::conv2d(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );

    SC_METHOD(thread_exitcond1_fu_210_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ki_reg_118 );

    SC_METHOD(thread_exitcond2_fu_194_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_reg_93 );

    SC_METHOD(thread_exitcond3_fu_152_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_reg_81 );

    SC_METHOD(thread_exitcond_fu_264_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( kj_reg_141 );

    SC_METHOD(thread_i_1_fu_158_p2);
    sensitive << ( i_reg_81 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_6_fu_289_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_j_1_fu_200_p2);
    sensitive << ( j_reg_93 );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_13_cast_fu_299_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ki_1_fu_216_p2);
    sensitive << ( ki_reg_118 );

    SC_METHOD(thread_ki_cast4_fu_206_p1);
    sensitive << ( ki_reg_118 );

    SC_METHOD(thread_kj_1_fu_270_p2);
    sensitive << ( kj_reg_141 );

    SC_METHOD(thread_kj_cast2_fu_260_p1);
    sensitive << ( kj_reg_141 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_7_cast_fu_255_p1 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( sum_reg_105 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_210_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_184_p1);
    sensitive << ( tmp_3_fu_176_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_236_p1);
    sensitive << ( tmp_9_fu_228_p3 );

    SC_METHOD(thread_p_shl_cast_fu_172_p1);
    sensitive << ( tmp_fu_164_p3 );

    SC_METHOD(thread_sum_2_fu_308_p2);
    sensitive << ( tmp_1_reg_380 );
    sensitive << ( sum_1_reg_129 );

    SC_METHOD(thread_tmp_10_fu_294_p2);
    sensitive << ( tmp_s_reg_347 );
    sensitive << ( kj_cast2_fu_260_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_299_p1);
    sensitive << ( tmp_10_fu_294_p2 );

    SC_METHOD(thread_tmp_1_fu_304_p2);
    sensitive << ( in_load_reg_370 );
    sensitive << ( kernel_load_reg_375 );

    SC_METHOD(thread_tmp_2_cast_fu_246_p1);
    sensitive << ( j_reg_93 );

    SC_METHOD(thread_tmp_2_fu_282_p3);
    sensitive << ( tmp_4_reg_342 );
    sensitive << ( tmp_8_fu_276_p2 );

    SC_METHOD(thread_tmp_3_fu_176_p3);
    sensitive << ( i_reg_81 );

    SC_METHOD(thread_tmp_4_fu_222_p2);
    sensitive << ( i_reg_81 );
    sensitive << ( ki_cast4_fu_206_p1 );

    SC_METHOD(thread_tmp_5_fu_188_p2);
    sensitive << ( p_shl_cast_fu_172_p1 );
    sensitive << ( p_shl1_cast_fu_184_p1 );

    SC_METHOD(thread_tmp_6_fu_289_p1);
    sensitive << ( tmp_2_fu_282_p3 );

    SC_METHOD(thread_tmp_7_cast_fu_255_p1);
    sensitive << ( tmp_7_fu_250_p2 );

    SC_METHOD(thread_tmp_7_fu_250_p2);
    sensitive << ( tmp_5_reg_321 );
    sensitive << ( tmp_2_cast_fu_246_p1 );

    SC_METHOD(thread_tmp_8_fu_276_p2);
    sensitive << ( j_reg_93 );
    sensitive << ( kj_cast2_fu_260_p1 );

    SC_METHOD(thread_tmp_9_fu_228_p3);
    sensitive << ( ki_reg_118 );

    SC_METHOD(thread_tmp_fu_164_p3);
    sensitive << ( i_reg_81 );

    SC_METHOD(thread_tmp_s_fu_240_p2);
    sensitive << ( ki_cast4_fu_206_p1 );
    sensitive << ( p_shl2_cast_fu_236_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_152_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_210_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond_fu_264_p2 );
    sensitive << ( exitcond2_fu_194_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, kernel_address0, "(port)kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "(port)kernel_ce0");
    sc_trace(mVcdFile, kernel_q0, "(port)kernel_q0");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_1_fu_158_p2, "i_1_fu_158_p2");
    sc_trace(mVcdFile, i_1_reg_316, "i_1_reg_316");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_5_fu_188_p2, "tmp_5_fu_188_p2");
    sc_trace(mVcdFile, tmp_5_reg_321, "tmp_5_reg_321");
    sc_trace(mVcdFile, exitcond3_fu_152_p2, "exitcond3_fu_152_p2");
    sc_trace(mVcdFile, j_1_fu_200_p2, "j_1_fu_200_p2");
    sc_trace(mVcdFile, j_1_reg_329, "j_1_reg_329");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ki_1_fu_216_p2, "ki_1_fu_216_p2");
    sc_trace(mVcdFile, ki_1_reg_337, "ki_1_reg_337");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_4_fu_222_p2, "tmp_4_fu_222_p2");
    sc_trace(mVcdFile, tmp_4_reg_342, "tmp_4_reg_342");
    sc_trace(mVcdFile, exitcond1_fu_210_p2, "exitcond1_fu_210_p2");
    sc_trace(mVcdFile, tmp_s_fu_240_p2, "tmp_s_fu_240_p2");
    sc_trace(mVcdFile, tmp_s_reg_347, "tmp_s_reg_347");
    sc_trace(mVcdFile, kj_1_fu_270_p2, "kj_1_fu_270_p2");
    sc_trace(mVcdFile, kj_1_reg_355, "kj_1_reg_355");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond_fu_264_p2, "exitcond_fu_264_p2");
    sc_trace(mVcdFile, in_load_reg_370, "in_load_reg_370");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, kernel_load_reg_375, "kernel_load_reg_375");
    sc_trace(mVcdFile, tmp_1_fu_304_p2, "tmp_1_fu_304_p2");
    sc_trace(mVcdFile, tmp_1_reg_380, "tmp_1_reg_380");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sum_2_fu_308_p2, "sum_2_fu_308_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, i_reg_81, "i_reg_81");
    sc_trace(mVcdFile, exitcond2_fu_194_p2, "exitcond2_fu_194_p2");
    sc_trace(mVcdFile, j_reg_93, "j_reg_93");
    sc_trace(mVcdFile, sum_reg_105, "sum_reg_105");
    sc_trace(mVcdFile, ki_reg_118, "ki_reg_118");
    sc_trace(mVcdFile, sum_1_reg_129, "sum_1_reg_129");
    sc_trace(mVcdFile, kj_reg_141, "kj_reg_141");
    sc_trace(mVcdFile, tmp_7_cast_fu_255_p1, "tmp_7_cast_fu_255_p1");
    sc_trace(mVcdFile, tmp_6_fu_289_p1, "tmp_6_fu_289_p1");
    sc_trace(mVcdFile, tmp_13_cast_fu_299_p1, "tmp_13_cast_fu_299_p1");
    sc_trace(mVcdFile, tmp_fu_164_p3, "tmp_fu_164_p3");
    sc_trace(mVcdFile, tmp_3_fu_176_p3, "tmp_3_fu_176_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_172_p1, "p_shl_cast_fu_172_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_184_p1, "p_shl1_cast_fu_184_p1");
    sc_trace(mVcdFile, ki_cast4_fu_206_p1, "ki_cast4_fu_206_p1");
    sc_trace(mVcdFile, tmp_9_fu_228_p3, "tmp_9_fu_228_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_236_p1, "p_shl2_cast_fu_236_p1");
    sc_trace(mVcdFile, tmp_2_cast_fu_246_p1, "tmp_2_cast_fu_246_p1");
    sc_trace(mVcdFile, tmp_7_fu_250_p2, "tmp_7_fu_250_p2");
    sc_trace(mVcdFile, kj_cast2_fu_260_p1, "kj_cast2_fu_260_p1");
    sc_trace(mVcdFile, tmp_8_fu_276_p2, "tmp_8_fu_276_p2");
    sc_trace(mVcdFile, tmp_2_fu_282_p3, "tmp_2_fu_282_p3");
    sc_trace(mVcdFile, tmp_10_fu_294_p2, "tmp_10_fu_294_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("conv2d.hdltvin.dat");
    mHdltvoutHandle.open("conv2d.hdltvout.dat");
}

conv2d::~conv2d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void conv2d::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_194_p2.read(), ap_const_lv1_1))) {
        i_reg_81 = i_1_reg_316.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_81 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_reg_93 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        j_reg_93 = j_1_reg_329.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_194_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ki_reg_118 = ap_const_lv2_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_264_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        ki_reg_118 = ki_1_reg_337.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        kj_reg_141 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        kj_reg_141 = kj_1_reg_355.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        sum_1_reg_129 = sum_reg_105.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        sum_1_reg_129 = sum_2_fu_308_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond2_fu_194_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        sum_reg_105 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(exitcond_fu_264_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        sum_reg_105 = sum_1_reg_129.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_1_reg_316 = i_1_fu_158_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        in_load_reg_370 = in_r_q0.read();
        kernel_load_reg_375 = kernel_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_1_reg_329 = j_1_fu_200_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ki_1_reg_337 = ki_1_fu_216_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kj_1_reg_355 = kj_1_fu_270_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_1_reg_380 = tmp_1_fu_304_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        tmp_4_reg_342 = tmp_4_fu_222_p2.read();
        tmp_s_reg_347 = tmp_s_fu_240_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_5_reg_321 = tmp_5_fu_188_p2.read();
    }
}

void conv2d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2d::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2d::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2d::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2d::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2d::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2d::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv2d::thread_ap_done() {
    if ((esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv2d::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv2d::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv2d::thread_exitcond1_fu_210_p2() {
    exitcond1_fu_210_p2 = (!ki_reg_118.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(ki_reg_118.read() == ap_const_lv2_3);
}

void conv2d::thread_exitcond2_fu_194_p2() {
    exitcond2_fu_194_p2 = (!j_reg_93.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_93.read() == ap_const_lv5_1E);
}

void conv2d::thread_exitcond3_fu_152_p2() {
    exitcond3_fu_152_p2 = (!i_reg_81.read().is_01() || !ap_const_lv5_1E.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_81.read() == ap_const_lv5_1E);
}

void conv2d::thread_exitcond_fu_264_p2() {
    exitcond_fu_264_p2 = (!kj_reg_141.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(kj_reg_141.read() == ap_const_lv2_3);
}

void conv2d::thread_i_1_fu_158_p2() {
    i_1_fu_158_p2 = (!i_reg_81.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_reg_81.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_in_r_address0() {
    in_r_address0 =  (sc_lv<10>) (tmp_6_fu_289_p1.read());
}

void conv2d::thread_in_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_j_1_fu_200_p2() {
    j_1_fu_200_p2 = (!j_reg_93.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_reg_93.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv2d::thread_kernel_address0() {
    kernel_address0 =  (sc_lv<4>) (tmp_13_cast_fu_299_p1.read());
}

void conv2d::thread_kernel_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_ki_1_fu_216_p2() {
    ki_1_fu_216_p2 = (!ki_reg_118.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ki_reg_118.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_ki_cast4_fu_206_p1() {
    ki_cast4_fu_206_p1 = esl_zext<5,2>(ki_reg_118.read());
}

void conv2d::thread_kj_1_fu_270_p2() {
    kj_1_fu_270_p2 = (!kj_reg_141.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kj_reg_141.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_kj_cast2_fu_260_p1() {
    kj_cast2_fu_260_p1 = esl_zext<5,2>(kj_reg_141.read());
}

void conv2d::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<10>) (tmp_7_cast_fu_255_p1.read());
}

void conv2d::thread_out_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_out_r_d0() {
    out_r_d0 = sum_reg_105.read();
}

void conv2d::thread_out_r_we0() {
    if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_p_shl1_cast_fu_184_p1() {
    p_shl1_cast_fu_184_p1 = esl_zext<11,6>(tmp_3_fu_176_p3.read());
}

void conv2d::thread_p_shl2_cast_fu_236_p1() {
    p_shl2_cast_fu_236_p1 = esl_zext<5,4>(tmp_9_fu_228_p3.read());
}

void conv2d::thread_p_shl_cast_fu_172_p1() {
    p_shl_cast_fu_172_p1 = esl_zext<11,10>(tmp_fu_164_p3.read());
}

void conv2d::thread_sum_2_fu_308_p2() {
    sum_2_fu_308_p2 = (!sum_1_reg_129.read().is_01() || !tmp_1_reg_380.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sum_1_reg_129.read()) + sc_biguint<32>(tmp_1_reg_380.read()));
}

void conv2d::thread_tmp_10_fu_294_p2() {
    tmp_10_fu_294_p2 = (!tmp_s_reg_347.read().is_01() || !kj_cast2_fu_260_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_s_reg_347.read()) + sc_biguint<5>(kj_cast2_fu_260_p1.read()));
}

void conv2d::thread_tmp_13_cast_fu_299_p1() {
    tmp_13_cast_fu_299_p1 = esl_sext<64,5>(tmp_10_fu_294_p2.read());
}

void conv2d::thread_tmp_1_fu_304_p2() {
    tmp_1_fu_304_p2 = (!kernel_load_reg_375.read().is_01() || !in_load_reg_370.read().is_01())? sc_lv<32>(): sc_bigint<32>(kernel_load_reg_375.read()) * sc_bigint<32>(in_load_reg_370.read());
}

void conv2d::thread_tmp_2_cast_fu_246_p1() {
    tmp_2_cast_fu_246_p1 = esl_zext<11,5>(j_reg_93.read());
}

void conv2d::thread_tmp_2_fu_282_p3() {
    tmp_2_fu_282_p3 = esl_concat<5,5>(tmp_4_reg_342.read(), tmp_8_fu_276_p2.read());
}

void conv2d::thread_tmp_3_fu_176_p3() {
    tmp_3_fu_176_p3 = esl_concat<5,1>(i_reg_81.read(), ap_const_lv1_0);
}

void conv2d::thread_tmp_4_fu_222_p2() {
    tmp_4_fu_222_p2 = (!ki_cast4_fu_206_p1.read().is_01() || !i_reg_81.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ki_cast4_fu_206_p1.read()) + sc_biguint<5>(i_reg_81.read()));
}

void conv2d::thread_tmp_5_fu_188_p2() {
    tmp_5_fu_188_p2 = (!p_shl_cast_fu_172_p1.read().is_01() || !p_shl1_cast_fu_184_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl_cast_fu_172_p1.read()) - sc_biguint<11>(p_shl1_cast_fu_184_p1.read()));
}

void conv2d::thread_tmp_6_fu_289_p1() {
    tmp_6_fu_289_p1 = esl_zext<64,10>(tmp_2_fu_282_p3.read());
}

void conv2d::thread_tmp_7_cast_fu_255_p1() {
    tmp_7_cast_fu_255_p1 = esl_sext<64,11>(tmp_7_fu_250_p2.read());
}

void conv2d::thread_tmp_7_fu_250_p2() {
    tmp_7_fu_250_p2 = (!tmp_5_reg_321.read().is_01() || !tmp_2_cast_fu_246_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_5_reg_321.read()) + sc_biguint<11>(tmp_2_cast_fu_246_p1.read()));
}

void conv2d::thread_tmp_8_fu_276_p2() {
    tmp_8_fu_276_p2 = (!kj_cast2_fu_260_p1.read().is_01() || !j_reg_93.read().is_01())? sc_lv<5>(): (sc_biguint<5>(kj_cast2_fu_260_p1.read()) + sc_biguint<5>(j_reg_93.read()));
}

void conv2d::thread_tmp_9_fu_228_p3() {
    tmp_9_fu_228_p3 = esl_concat<2,2>(ki_reg_118.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_fu_164_p3() {
    tmp_fu_164_p3 = esl_concat<5,5>(i_reg_81.read(), ap_const_lv5_0);
}

void conv2d::thread_tmp_s_fu_240_p2() {
    tmp_s_fu_240_p2 = (!p_shl2_cast_fu_236_p1.read().is_01() || !ki_cast4_fu_206_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl2_cast_fu_236_p1.read()) - sc_biguint<5>(ki_cast4_fu_206_p1.read()));
}

void conv2d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond3_fu_152_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond2_fu_194_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(exitcond1_fu_210_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(exitcond_fu_264_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

void conv2d::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_address0\" :  \"" << in_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_ce0\" :  \"" << in_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_q0\" :  \"" << in_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_address0\" :  \"" << kernel_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"kernel_ce0\" :  \"" << kernel_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"kernel_q0\" :  \"" << kernel_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_address0\" :  \"" << out_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ce0\" :  \"" << out_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_we0\" :  \"" << out_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_d0\" :  \"" << out_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

