// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv2d_HH_
#define _conv2d_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct conv2d : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > in_r_address0;
    sc_out< sc_logic > in_r_ce0;
    sc_in< sc_lv<32> > in_r_q0;
    sc_out< sc_lv<4> > kernel_address0;
    sc_out< sc_logic > kernel_ce0;
    sc_in< sc_lv<32> > kernel_q0;
    sc_out< sc_lv<10> > out_r_address0;
    sc_out< sc_logic > out_r_ce0;
    sc_out< sc_logic > out_r_we0;
    sc_out< sc_lv<32> > out_r_d0;


    // Module declarations
    conv2d(sc_module_name name);
    SC_HAS_PROCESS(conv2d);

    ~conv2d();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<8> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<5> > i_1_fu_158_p2;
    sc_signal< sc_lv<5> > i_1_reg_316;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<11> > tmp_5_fu_188_p2;
    sc_signal< sc_lv<11> > tmp_5_reg_321;
    sc_signal< sc_lv<1> > exitcond3_fu_152_p2;
    sc_signal< sc_lv<5> > j_1_fu_200_p2;
    sc_signal< sc_lv<5> > j_1_reg_329;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<2> > ki_1_fu_216_p2;
    sc_signal< sc_lv<2> > ki_1_reg_337;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<5> > tmp_4_fu_222_p2;
    sc_signal< sc_lv<5> > tmp_4_reg_342;
    sc_signal< sc_lv<1> > exitcond1_fu_210_p2;
    sc_signal< sc_lv<5> > tmp_s_fu_240_p2;
    sc_signal< sc_lv<5> > tmp_s_reg_347;
    sc_signal< sc_lv<2> > kj_1_fu_270_p2;
    sc_signal< sc_lv<2> > kj_1_reg_355;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > exitcond_fu_264_p2;
    sc_signal< sc_lv<32> > in_load_reg_370;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > kernel_load_reg_375;
    sc_signal< sc_lv<32> > tmp_1_fu_304_p2;
    sc_signal< sc_lv<32> > tmp_1_reg_380;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > sum_2_fu_308_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<5> > i_reg_81;
    sc_signal< sc_lv<1> > exitcond2_fu_194_p2;
    sc_signal< sc_lv<5> > j_reg_93;
    sc_signal< sc_lv<32> > sum_reg_105;
    sc_signal< sc_lv<2> > ki_reg_118;
    sc_signal< sc_lv<32> > sum_1_reg_129;
    sc_signal< sc_lv<2> > kj_reg_141;
    sc_signal< sc_lv<64> > tmp_7_cast_fu_255_p1;
    sc_signal< sc_lv<64> > tmp_6_fu_289_p1;
    sc_signal< sc_lv<64> > tmp_13_cast_fu_299_p1;
    sc_signal< sc_lv<10> > tmp_fu_164_p3;
    sc_signal< sc_lv<6> > tmp_3_fu_176_p3;
    sc_signal< sc_lv<11> > p_shl_cast_fu_172_p1;
    sc_signal< sc_lv<11> > p_shl1_cast_fu_184_p1;
    sc_signal< sc_lv<5> > ki_cast4_fu_206_p1;
    sc_signal< sc_lv<4> > tmp_9_fu_228_p3;
    sc_signal< sc_lv<5> > p_shl2_cast_fu_236_p1;
    sc_signal< sc_lv<11> > tmp_2_cast_fu_246_p1;
    sc_signal< sc_lv<11> > tmp_7_fu_250_p2;
    sc_signal< sc_lv<5> > kj_cast2_fu_260_p1;
    sc_signal< sc_lv<5> > tmp_8_fu_276_p2;
    sc_signal< sc_lv<10> > tmp_2_fu_282_p3;
    sc_signal< sc_lv<5> > tmp_10_fu_294_p2;
    sc_signal< sc_lv<8> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_ST_fsm_state1;
    static const sc_lv<8> ap_ST_fsm_state2;
    static const sc_lv<8> ap_ST_fsm_state3;
    static const sc_lv<8> ap_ST_fsm_state4;
    static const sc_lv<8> ap_ST_fsm_state5;
    static const sc_lv<8> ap_ST_fsm_state6;
    static const sc_lv<8> ap_ST_fsm_state7;
    static const sc_lv<8> ap_ST_fsm_state8;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<5> ap_const_lv5_1E;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond1_fu_210_p2();
    void thread_exitcond2_fu_194_p2();
    void thread_exitcond3_fu_152_p2();
    void thread_exitcond_fu_264_p2();
    void thread_i_1_fu_158_p2();
    void thread_in_r_address0();
    void thread_in_r_ce0();
    void thread_j_1_fu_200_p2();
    void thread_kernel_address0();
    void thread_kernel_ce0();
    void thread_ki_1_fu_216_p2();
    void thread_ki_cast4_fu_206_p1();
    void thread_kj_1_fu_270_p2();
    void thread_kj_cast2_fu_260_p1();
    void thread_out_r_address0();
    void thread_out_r_ce0();
    void thread_out_r_d0();
    void thread_out_r_we0();
    void thread_p_shl1_cast_fu_184_p1();
    void thread_p_shl2_cast_fu_236_p1();
    void thread_p_shl_cast_fu_172_p1();
    void thread_sum_2_fu_308_p2();
    void thread_tmp_10_fu_294_p2();
    void thread_tmp_13_cast_fu_299_p1();
    void thread_tmp_1_fu_304_p2();
    void thread_tmp_2_cast_fu_246_p1();
    void thread_tmp_2_fu_282_p3();
    void thread_tmp_3_fu_176_p3();
    void thread_tmp_4_fu_222_p2();
    void thread_tmp_5_fu_188_p2();
    void thread_tmp_6_fu_289_p1();
    void thread_tmp_7_cast_fu_255_p1();
    void thread_tmp_7_fu_250_p2();
    void thread_tmp_8_fu_276_p2();
    void thread_tmp_9_fu_228_p3();
    void thread_tmp_fu_164_p3();
    void thread_tmp_s_fu_240_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
