-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv2d is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_r_ce0 : OUT STD_LOGIC;
    in_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    kernel_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    kernel_ce0 : OUT STD_LOGIC;
    kernel_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of conv2d is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "conv2d,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.510000,HLS_SYN_LAT=39661,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=216,HLS_SYN_LUT=331,HLS_VERSION=2018_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv5_1E : STD_LOGIC_VECTOR (4 downto 0) := "11110";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal i_1_fu_158_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal i_1_reg_316 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_5_fu_188_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_5_reg_321 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond3_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_1_fu_200_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal j_1_reg_329 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ki_1_fu_216_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ki_1_reg_337 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_4_fu_222_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_342 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond1_fu_210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_240_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_reg_347 : STD_LOGIC_VECTOR (4 downto 0);
    signal kj_1_fu_270_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kj_1_reg_355 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal exitcond_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_load_reg_370 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal kernel_load_reg_375 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_reg_380 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sum_2_fu_308_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal i_reg_81 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond2_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_reg_93 : STD_LOGIC_VECTOR (4 downto 0);
    signal sum_reg_105 : STD_LOGIC_VECTOR (31 downto 0);
    signal ki_reg_118 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_reg_129 : STD_LOGIC_VECTOR (31 downto 0);
    signal kj_reg_141 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_7_cast_fu_255_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_6_fu_289_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_13_cast_fu_299_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_164_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_176_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_cast_fu_172_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_shl1_cast_fu_184_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ki_cast4_fu_206_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_9_fu_228_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl2_cast_fu_236_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_cast_fu_246_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_250_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal kj_cast2_fu_260_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_fu_276_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_282_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_fu_294_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_reg_81_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_194_p2 = ap_const_lv1_1))) then 
                i_reg_81 <= i_1_reg_316;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_81 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    j_reg_93_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_reg_93 <= ap_const_lv5_0;
            elsif (((exitcond1_fu_210_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                j_reg_93 <= j_1_reg_329;
            end if; 
        end if;
    end process;

    ki_reg_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_194_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                ki_reg_118 <= ap_const_lv2_0;
            elsif (((exitcond_fu_264_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                ki_reg_118 <= ki_1_reg_337;
            end if; 
        end if;
    end process;

    kj_reg_141_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_210_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                kj_reg_141 <= ap_const_lv2_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                kj_reg_141 <= kj_1_reg_355;
            end if; 
        end if;
    end process;

    sum_1_reg_129_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_210_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sum_1_reg_129 <= sum_reg_105;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                sum_1_reg_129 <= sum_2_fu_308_p2;
            end if; 
        end if;
    end process;

    sum_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_194_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                sum_reg_105 <= ap_const_lv32_0;
            elsif (((exitcond_fu_264_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                sum_reg_105 <= sum_1_reg_129;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_1_reg_316 <= i_1_fu_158_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                in_load_reg_370 <= in_r_q0;
                kernel_load_reg_375 <= kernel_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                j_1_reg_329 <= j_1_fu_200_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                ki_1_reg_337 <= ki_1_fu_216_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                kj_1_reg_355 <= kj_1_fu_270_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                tmp_1_reg_380 <= tmp_1_fu_304_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_210_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                tmp_4_reg_342 <= tmp_4_fu_222_p2;
                tmp_s_reg_347 <= tmp_s_fu_240_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_152_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    tmp_5_reg_321(10 downto 1) <= tmp_5_fu_188_p2(10 downto 1);
            end if;
        end if;
    end process;
    tmp_5_reg_321(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond3_fu_152_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, exitcond1_fu_210_p2, ap_CS_fsm_state5, exitcond_fu_264_p2, exitcond2_fu_194_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (exitcond2_fu_194_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((exitcond1_fu_210_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((exitcond_fu_264_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);

    ap_done_assign_proc : process(ap_CS_fsm_state2, exitcond3_fu_152_p2)
    begin
        if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond3_fu_152_p2)
    begin
        if (((exitcond3_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_fu_210_p2 <= "1" when (ki_reg_118 = ap_const_lv2_3) else "0";
    exitcond2_fu_194_p2 <= "1" when (j_reg_93 = ap_const_lv5_1E) else "0";
    exitcond3_fu_152_p2 <= "1" when (i_reg_81 = ap_const_lv5_1E) else "0";
    exitcond_fu_264_p2 <= "1" when (kj_reg_141 = ap_const_lv2_3) else "0";
    i_1_fu_158_p2 <= std_logic_vector(unsigned(i_reg_81) + unsigned(ap_const_lv5_1));
    in_r_address0 <= tmp_6_fu_289_p1(10 - 1 downto 0);

    in_r_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_r_ce0 <= ap_const_logic_1;
        else 
            in_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    j_1_fu_200_p2 <= std_logic_vector(unsigned(j_reg_93) + unsigned(ap_const_lv5_1));
    kernel_address0 <= tmp_13_cast_fu_299_p1(4 - 1 downto 0);

    kernel_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            kernel_ce0 <= ap_const_logic_1;
        else 
            kernel_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ki_1_fu_216_p2 <= std_logic_vector(unsigned(ki_reg_118) + unsigned(ap_const_lv2_1));
    ki_cast4_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ki_reg_118),5));
    kj_1_fu_270_p2 <= std_logic_vector(unsigned(kj_reg_141) + unsigned(ap_const_lv2_1));
    kj_cast2_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kj_reg_141),5));
    out_r_address0 <= tmp_7_cast_fu_255_p1(10 - 1 downto 0);

    out_r_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            out_r_ce0 <= ap_const_logic_1;
        else 
            out_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    out_r_d0 <= sum_reg_105;

    out_r_we0_assign_proc : process(ap_CS_fsm_state4, exitcond1_fu_210_p2)
    begin
        if (((exitcond1_fu_210_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            out_r_we0 <= ap_const_logic_1;
        else 
            out_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_176_p3),11));
    p_shl2_cast_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_228_p3),5));
    p_shl_cast_fu_172_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_164_p3),11));
    sum_2_fu_308_p2 <= std_logic_vector(unsigned(sum_1_reg_129) + unsigned(tmp_1_reg_380));
    tmp_10_fu_294_p2 <= std_logic_vector(unsigned(tmp_s_reg_347) + unsigned(kj_cast2_fu_260_p1));
        tmp_13_cast_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_294_p2),64));

    tmp_1_fu_304_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(kernel_load_reg_375) * signed(in_load_reg_370))), 32));
    tmp_2_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_reg_93),11));
    tmp_2_fu_282_p3 <= (tmp_4_reg_342 & tmp_8_fu_276_p2);
    tmp_3_fu_176_p3 <= (i_reg_81 & ap_const_lv1_0);
    tmp_4_fu_222_p2 <= std_logic_vector(unsigned(ki_cast4_fu_206_p1) + unsigned(i_reg_81));
    tmp_5_fu_188_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_172_p1) - unsigned(p_shl1_cast_fu_184_p1));
    tmp_6_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_282_p3),64));
        tmp_7_cast_fu_255_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_7_fu_250_p2),64));

    tmp_7_fu_250_p2 <= std_logic_vector(unsigned(tmp_5_reg_321) + unsigned(tmp_2_cast_fu_246_p1));
    tmp_8_fu_276_p2 <= std_logic_vector(unsigned(kj_cast2_fu_260_p1) + unsigned(j_reg_93));
    tmp_9_fu_228_p3 <= (ki_reg_118 & ap_const_lv2_0);
    tmp_fu_164_p3 <= (i_reg_81 & ap_const_lv5_0);
    tmp_s_fu_240_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_236_p1) - unsigned(ki_cast4_fu_206_p1));
end behav;
